# =========================== Basic Settings ===========================
# machine info
num_gpus_per_job: 8  # number of gpus each job need

# data
dataset: imagenet1k
data_transforms: imagenet1k
data_loader: imagenet1k
dataset_dir: data
data_loader_workers: 5

# info
num_classes: 1000
image_size: 224 
topk: [1, 5]
num_epochs: 1

# optimizer
optimizer: sgd 
momentum: 0.9 
weight_decay: 0.0001
nesterov: True

# lr
lr: 0.0
lr_scheduler: constant


# pretrain, resume, test_only
pretrained_dir: ''
pretrained_file: ''
resume: ''
test_only: False

#
random_seed: 1995
model: ''
reset_parameters: True

#
distributed: False
distributed_all_reduce: False
use_diff_seed: False

#
rescale_forward: True
rescale_forward_conv: False
normalize: True
rescale_type: constant #[stddev, constant]

#
weight_format: [8, 7]
input_format: [8, 6]

#
format_type: per_layer #[~, per_model, per_layer, per_channel]

#
format_from_metric: True
momentum_for_metric: 0.1
metric: std

finetune_iters: 100
ptcv_pretrained: True

no_clipping: True
input_fraclen_sharing: False

format_grid_search: True

#
weight_decay_scheme: no_depthwise_no_bn #[all, only_no_depthwise, only_no_bn, no_depthwise_no_bn]

# =========================== Override Settings ===========================
quant_bias: True
quant_avgpool: True
pool_fusing: True
quant_maxpool: False #True ## Onnx does not support unfold used in MaxPool
int_infer: True ## For int model
integize: True ## For gpu inference
int_op_only: False ## For cpu inference
integize_file_path: /home/cheng/projects/F8Net-per-channel/log/ptcv_pretrained_True/nvidia_pretrained_False/hawq_pretrained_False/finetune_iters_10/bn_calib_before_test_False/bn_calib_batch_num_-1/quant_avgpool_False/pool_fusing_False/weight_format_wl_8_fl_7/input_format_wl_8_fl_6/rescale_forward_True/rescale_forward_conv_False/rescale_type_constant/input_fraclen_sharing_False/floating_model_False/floating_wo_clip_False/no_clipping_True/fp_pretrained_False/format_type_per_channel/format_from_metric_True/momentum_for_metric_0.1/metric_std/format_grid_search_False/bn_momentum_0.1/bn_eps_0.1/lr_0.0/weight_decay_scheme_no_depthwise_no_bn/normalize_True/warmup_epochs_0/weight_decay_0.0001/8bit
int_op_only_file_path: '' #/path/to/pretrained_models/ImageNet/tiny_finetuning/ResNet18/ptcv_pretrained/8bit
print_each_iter: True

pretrained_file: /home/cheng/projects/F8Net-per-channel/log/ptcv_pretrained_True/nvidia_pretrained_False/hawq_pretrained_False/finetune_iters_10/bn_calib_before_test_False/bn_calib_batch_num_-1/quant_avgpool_False/pool_fusing_False/weight_format_wl_8_fl_7/input_format_wl_8_fl_6/rescale_forward_True/rescale_forward_conv_False/rescale_type_constant/input_fraclen_sharing_False/floating_model_False/floating_wo_clip_False/no_clipping_True/fp_pretrained_False/format_type_per_channel/format_from_metric_True/momentum_for_metric_0.1/metric_std/format_grid_search_False/bn_momentum_0.1/bn_eps_0.1/lr_0.0/weight_decay_scheme_no_depthwise_no_bn/normalize_True/warmup_epochs_0/weight_decay_0.0001/best_model.pt
test_only: True
log_dir: /home/cheng/projects/F8Net-per-channel/log/
model: models.fix_resnet
depth: 18
format_type: per_channel
format_from_metric: true
format_grid_search: false